/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import org.junit.Test;
import static org.junit.Assert.*;

public class ServerTest {
    // unit tests are not currently used client-side
}
